export const countries = [
    { code: "us", name: "United States", states: ["California", "Texas", "Florida", "New York", "Illinois", "Washington"] },
    { code: "ca", name: "Canada", states: ["Ontario", "Quebec", "British Columbia", "Alberta", "Manitoba"] },
    { code: "in", name: "India", states: ["Maharashtra", "Karnataka", "Delhi", "West Bengal", "Tamil Nadu", "Gujarat"] },
    { code: "gb", name: "United Kingdom", states: ["England", "Scotland", "Wales", "Northern Ireland"] },
    { code: "au", name: "Australia", states: ["New South Wales", "Victoria", "Queensland", "Western Australia", "South Australia"] },
    { code: "de", name: "Germany", states: ["Bavaria", "Berlin", "Hamburg", "Hesse", "Saxony"] },
    { code: "fr", name: "France", states: ["Île-de-France", "Provence-Alpes-Côte d'Azur", "Normandy", "Brittany", "Occitanie"] },
    { code: "it", name: "Italy", states: ["Lombardy", "Lazio", "Campania", "Veneto", "Tuscany"] },
    { code: "es", name: "Spain", states: ["Catalonia", "Andalusia", "Madrid", "Valencia", "Galicia"] },
    { code: "jp", name: "Japan", states: ["Tokyo", "Osaka", "Kyoto", "Hokkaido", "Fukuoka"] },
    { code: "cn", name: "China", states: ["Beijing", "Shanghai", "Guangdong", "Sichuan", "Zhejiang"] },
    { code: "br", name: "Brazil", states: ["São Paulo", "Rio de Janeiro", "Bahia", "Minas Gerais", "Paraná"] },
    { code: "mx", name: "Mexico", states: ["Mexico City", "Jalisco", "Nuevo León", "Yucatán", "Puebla"] },
    { code: "za", name: "South Africa", states: ["Gauteng", "Western Cape", "KwaZulu-Natal", "Eastern Cape", "Free State"] },
    { code: "ru", name: "Russia", states: ["Moscow", "Saint Petersburg", "Siberia", "Krasnodar", "Tatarstan"] },
    { code: "ae", name: "United Arab Emirates", states: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Ras Al Khaimah"] },
    { code: "ar", name: "Argentina", states: ["Buenos Aires", "Córdoba", "Santa Fe", "Mendoza", "Tucumán"] },
    { code: "id", name: "Indonesia", states: ["Jakarta", "Bali", "West Java", "East Java", "Sumatra"] },
    { code: "kr", name: "South Korea", states: ["Seoul", "Busan", "Incheon", "Daegu", "Gwangju"] },
    { code: "tr", name: "Turkey", states: ["Istanbul", "Ankara", "Izmir", "Antalya", "Bursa"] },
    { code: "sa", name: "Saudi Arabia", states: ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam"] },
    { code: "eg", name: "Egypt", states: ["Cairo", "Alexandria", "Giza", "Luxor", "Aswan"] },
    { code: "pk", name: "Pakistan", states: ["Punjab", "Sindh", "Khyber Pakhtunkhwa", "Balochistan", "Islamabad"] },
    { code: "bd", name: "Bangladesh", states: ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet"] },
    { code: "ng", name: "Nigeria", states: ["Lagos", "Kano", "Abuja", "Rivers", "Kaduna"] },
    { code: "ph", name: "Philippines", states: ["Metro Manila", "Cebu", "Davao", "Iloilo", "Baguio"] },
    { code: "nl", name: "Netherlands", states: ["North Holland", "South Holland", "Utrecht", "Gelderland", "Limburg"] },
    { code: "se", name: "Sweden", states: ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västra Götaland"] },
    { code: "ch", name: "Switzerland", states: ["Zurich", "Geneva", "Basel", "Bern", "Lucerne"] },
    { code: "be", name: "Belgium", states: ["Brussels", "Flanders", "Wallonia", "Antwerp", "Ghent"] },
    { code: "at", name: "Austria", states: ["Vienna", "Salzburg", "Tyrol", "Styria", "Upper Austria"] },
    { code: "th", name: "Thailand", states: ["Bangkok", "Chiang Mai", "Phuket", "Pattaya", "Krabi"] },
    { code: "vn", name: "Vietnam", states: ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hue", "Hai Phong"] },
    { code: "pl", name: "Poland", states: ["Warsaw", "Kraków", "Wrocław", "Poznań", "Gdańsk"] },
    { code: "gr", name: "Greece", states: ["Athens", "Thessaloniki", "Crete", "Rhodes", "Santorini"] },
];
  