export const tagOptions = [
    "Medical Expenses",
    "Surgery & Treatment",
    "Education Support",
    "School & College Fees",
    "Scholarships",
    "Disaster Relief",
    "Flood & Earthquake Relief",
    "Animal Welfare",
    "Pet Medical Aid",
    "Wildlife Conservation",
    "Community Projects",
    "Local Fundraising",
    "Homeless Shelter Support",
    "Startup Funding",
    "Business Expansion",
    "Technology & Innovation",
    "Emergency Assistance",
    "Fire & Accident Recovery",
    "Creative Projects",
    "Film & Video Production",
    "Music & Arts Support",
    "Memorial & Funeral Costs",
    "Family Support",
    "Legal Assistance",
    "Environmental Causes",
    "Charity & Non-Profit",
    "Religious Causes",
];