-- AlterTable
ALTER TABLE "Campaign" ALTER COLUMN "raised" SET DEFAULT 0.0,
ALTER COLUMN "raised" SET DATA TYPE DECIMAL(78,18),
ALTER COLUMN "Goal" SET DEFAULT 0.0,
ALTER COLUMN "Goal" SET DATA TYPE DECIMAL(78,18);

-- AlterTable
ALTER TABLE "CampaignMetadata" ALTER COLUMN "goal" SET DEFAULT '0.0';
